#############################################################################
# Makefile for building: buttonAlert.app/Contents/MacOS/buttonAlert
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  button_alert.pro
# Template: app
# Command: /Users/jknick/Qt/5.4/clang_64/bin/qmake -o Makefile button_alert.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I. -I../../Qt/5.4/clang_64/lib/QtQuick.framework/Versions/5/Headers -I../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../Qt/5.4/clang_64/lib/QtQml.framework/Versions/5/Headers -I../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../Qt/5.4/clang_64/mkspecs/macx-clang -F/Users/jknick/Qt/5.4/clang_64/lib
QMAKE         = /Users/jknick/Qt/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = buttonAlert1.0.0
DISTDIR = /Users/jknick/proj/buttonAlertORIG/.tmp/buttonAlert1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/jknick/Qt/5.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/jknick/Qt/5.4/clang_64/lib -framework QtQuick -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtQml -framework QtNetwork -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_button_alert.cpp \
		moc_fileio.cpp
OBJECTS       = main.o \
		qrc_button_alert.o \
		moc_fileio.o
DIST          = ../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.4/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		button_alert.pro fileio.h main.cpp
QMAKE_TARGET  = buttonAlert
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = buttonAlert.app/Contents/MacOS/buttonAlert

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d buttonAlert.app/Contents/MacOS/ || mkdir -p buttonAlert.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: button_alert.pro ../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.4/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		button_alert.pro \
		button_alert.qrc \
		/Users/jknick/Qt/5.4/clang_64/lib/QtQuick.framework/QtQuick.prl \
		/Users/jknick/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/jknick/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/jknick/Qt/5.4/clang_64/lib/QtQml.framework/QtQml.prl \
		/Users/jknick/Qt/5.4/clang_64/lib/QtNetwork.framework/QtNetwork.prl
	$(QMAKE) -o Makefile button_alert.pro
../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.4/clang_64/mkspecs/qdevice.pri:
../../Qt/5.4/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf:
../../Qt/5.4/clang_64/mkspecs/common/unix.conf:
../../Qt/5.4/clang_64/mkspecs/common/mac.conf:
../../Qt/5.4/clang_64/mkspecs/common/macx.conf:
../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.4/clang_64/mkspecs/common/clang.conf:
../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.4/clang_64/mkspecs/qconfig.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.4/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.4/clang_64/mkspecs/features/qt.prf:
../../Qt/5.4/clang_64/mkspecs/features/resources.prf:
../../Qt/5.4/clang_64/mkspecs/features/moc.prf:
../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.4/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.4/clang_64/mkspecs/features/lex.prf:
button_alert.pro:
button_alert.qrc:
/Users/jknick/Qt/5.4/clang_64/lib/QtQuick.framework/QtQuick.prl:
/Users/jknick/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/jknick/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/jknick/Qt/5.4/clang_64/lib/QtQml.framework/QtQml.prl:
/Users/jknick/Qt/5.4/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile button_alert.pro

qmake_all: FORCE

buttonAlert.app/Contents/PkgInfo: 
	@test -d buttonAlert.app/Contents || mkdir -p buttonAlert.app/Contents
	@$(DEL_FILE) buttonAlert.app/Contents/PkgInfo
	@echo "APPL????" >buttonAlert.app/Contents/PkgInfo
buttonAlert.app/Contents/Resources/empty.lproj: 
	@test -d buttonAlert.app/Contents/Resources || mkdir -p buttonAlert.app/Contents/Resources
	@touch buttonAlert.app/Contents/Resources/empty.lproj
	
buttonAlert.app/Contents/Info.plist: 
	@test -d buttonAlert.app/Contents || mkdir -p buttonAlert.app/Contents
	@$(DEL_FILE) buttonAlert.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.knick.buttonAlert,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,buttonAlert,g" -e "s,@TYPEINFO@,????,g" ../../Qt/5.4/clang_64/mkspecs/macx-clang/Info.plist.app >buttonAlert.app/Contents/Info.plist

all: Makefile \
		buttonAlert.app/Contents/PkgInfo \
		buttonAlert.app/Contents/Resources/empty.lproj \
		buttonAlert.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents button_alert.qrc $(DISTDIR)/
	$(COPY_FILE) --parents fileio.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r buttonAlert.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_button_alert.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_button_alert.cpp
qrc_button_alert.cpp: button_alert.qrc \
		qml/main.qml \
		audio/10mark.wav \
		audio/20mark.wav \
		audio/30mark.wav \
		audio/40mark.wav \
		audio/50mark.wav \
		audio/new_low.wav
	/Users/jknick/Qt/5.4/clang_64/bin/rcc -name button_alert button_alert.qrc -o qrc_button_alert.cpp

compiler_moc_header_make_all: moc_fileio.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_fileio.cpp
moc_fileio.cpp: ../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		fileio.h
	/Users/jknick/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/jknick/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/jknick/proj/buttonAlertORIG -I/Users/jknick/Qt/5.4/clang_64/lib/QtQuick.framework/Headers -I/Users/jknick/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/jknick/Qt/5.4/clang_64/lib/QtQml.framework/Headers -I/Users/jknick/Qt/5.4/clang_64/lib/QtNetwork.framework/Headers -I/Users/jknick/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/jknick/Qt/5.4/clang_64/lib fileio.h -o moc_fileio.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QGuiApplication \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qguiapplication.h \
		../../Qt/5.4/clang_64/lib/QtQuick.framework/Versions/5/Headers/QQuickView \
		../../Qt/5.4/clang_64/lib/QtQuick.framework/Versions/5/Headers/qquickview.h \
		../../Qt/5.4/clang_64/lib/QtQml.framework/Versions/5/Headers/QQmlContext \
		../../Qt/5.4/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlcontext.h \
		../../Qt/5.4/clang_64/lib/QtQml.framework/Versions/5/Headers/QQmlEngine \
		../../Qt/5.4/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlengine.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDir \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdir.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		fileio.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_button_alert.o: qrc_button_alert.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_button_alert.o qrc_button_alert.cpp

moc_fileio.o: moc_fileio.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fileio.o moc_fileio.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

